### ISSUE TITLE
Running YETI on Win7 causes error every single time

### ISSUE THREAD

**Issue by alexsaves** [yui/yeti#36]
If I run yeti with virtually any parameters, I just get this:

? Whoops! TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Configuration.configurationFinder [as locate](C:Usersalexei.whiteAppDataRoamingnpmnode_modulesyetilibcliconfiguration.js:52:37)
    at Configuration.proto.importFromDirectory (C:\Users\alexei.white\AppData\Roaming\npm\node_modules\yeti\lib\cli\configuration.js:184:37)
    at Configuration.proto.home (C:\Users\alexei.white\AppData\Roaming\npm\node_modules\yeti\lib\cli\configuration.js:219:10)
    at CLI.route (C:\Users\alexei.white\AppData\Roaming\npm\node_modules\yeti\lib\cli\index.js:616:34)
    at Object.<anonymous> (C:\Users\alexei.white\AppData\Roaming\npm\node_modules\yeti\cli.js:16:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

If you believe this is a bug in Yeti, please report it.
    http://yuilibrary.com/projects/yeti/report
    Yeti v0.2.21
    Node.js v0.10.4

**Comment by reid** [comment]
Thanks for reporting this issue. I'm sorry for the trouble.

I'm currently working on other projects, so it may take longer than a week for me to resolve Windows-specific flakiness in Yeti. I know that other platform-specific problems are present that don't apply to Linux and OS X.

I would very much appreciate a pull request that fixes Yeti for Windows 7, if you're able to help. Let me know. I'd love to have them fixed!

**Comment by alexsaves** [comment]
No worries. It's a promising tool. I wish Yahoo had more resources to devote to it. I did mess around with configuration.js for a little while. I managed to get past this issue but then ran into another one that seemed more serious. I don't feel comfortable yet trying to seriously solve these issues properly. If I get a few more hours to work on it I might take another stab.

It would be neat if at some point you could bake in web tunnel support for BrowserStack. I'm waiting for one of these browser launcher tools to do that out of the box. Would be a game changer for us, certainly. Just an idle feature request!

**Comment by luozhihua** [comment]
windows 8 had throw a same error

**Comment by busykai** [comment]
You need to set HOME environment variable before you run yeti.

set HOME=c:\Users<your Windows username>

**Comment by reid** [comment]
@busykai Thanks for the tip!
