### ISSUE TITLE
Error in Node 0.10.11 on Windows

### ISSUE THREAD

**Issue by juandopazo** [yui/yeti#52]
Hi!

I'm getting the following error when running yeti 0.2.22 in Node 0.10.11 on Windows:

```
✗ Whoops! TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Configuration.configurationFinder [as locate] (C:\Users\Juan Ignacio\AppD
ata\Roaming\npm\node_modules\yeti\lib\cli\configuration.js:52:40)
    at Configuration.proto.importFromDirectory (C:\Users\Juan Ignacio\AppData\Ro
aming\npm\node_modules\yeti\lib\cli\configuration.js:184:37)
    at Configuration.proto.home (C:\Users\Juan Ignacio\AppData\Roaming\npm\node_
modules\yeti\lib\cli\configuration.js:219:10)
    at CLI.route (C:\Users\Juan Ignacio\AppData\Roaming\npm\node_modules\yeti\li
b\cli\index.js:616:34)
    at Object.<anonymous> (C:\Users\Juan Ignacio\AppData\Roaming\npm\node_module
s\yeti\cli.js:16:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by juandopazo** [comment]
Dupe to #36
