### ISSUE TITLE
when start a test in sauce with two browsers got an error

### ISSUE THREAD

**Issue by cpanato** [yui/yeti#73]
Command line:
yeti --browser chrome/Linux --browser ff test-runner/*.html

tried with firefox also. In sasuce it start the two browsers.

Output
Waiting for Hub to launch browsers...
✗ Whoops! Error: Remote error for method: batch, message: Failed to connect to WebDriver host at {"host":"ondemand.saucelabs.com","port":"80","user":"XXXXX","pass":"XXXX"} because The environment you requested was unavailable.
    at BlizzardSession.invokeRPC (/usr/lib/node_modules/yeti/lib/blizzard/session.js:473:21)
    at BlizzardSession.onMessage (/usr/lib/node_modules/yeti/lib/blizzard/session.js:602:18)
    at BlizzardSession.EventEmitter.emit (/usr/lib/node_modules/yeti/node_modules/eventemitter2/lib/eventemitter2.js:332:22)
    at BlizzardSession.onIncomingJSON (/usr/lib/node_modules/yeti/lib/blizzard/session.js:537:10)
    at BlizzardSession.EventEmitter.emit (/usr/lib/node_modules/yeti/node_modules/eventemitter2/lib/eventemitter2.js:332:22)
    at /usr/lib/node_modules/yeti/lib/blizzard/session.js:804:18
    at Socket.emitter (/usr/lib/node_modules/yeti/lib/blizzard/session.js:782:21)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)

If you believe this is a bug in Yeti, please report it.
    http://yuilibrary.com/projects/yeti/report
    Yeti v0.2.24
    Node.js v0.10.15

**Comment by reid** [comment]
Hi there,

You'll need to provide an operating system and version in addition to "firefox", otherwise Sauce Labs won't be able to launch because it doesn't know exactly what you want.

Example: `--browser firefox/26/xp`.

Better yet, try the new `--caps` option for more control.

Example: `--caps 'browserName=firefox;version=26;platform=Windows XP'`

You can see the details you should supply to caps by visiting https://saucelabs.com/platforms and selecting "node.js" from the dropdown.

Closing because this doesn't appear to be a bug in Yeti. Let me know if you still need help.

**Comment by cpanato** [comment]
@reid thanks.
quick question to use caps with more than 1 browser i just add more like this?

```
--caps '{[browserName=firefox;version=26;platform=Windows XP],[ browserName=chrome;version=32;platform=Linux]}'
```

if not how to proceed?

thanks again

**Comment by reid** [comment]
@ctadeu Try:

```
--caps 'browserName=firefox;version=26;platform=Windows XP' --caps 'browserName=chrome;version=32;platform=Linux'
```

Each `--caps` option will launch a browser with those capabilities.

**Comment by cpanato** [comment]
@reid works thanks
