### ISSUE TITLE
Crash with "TypeError: Cannot call method 'serve' of null"

### ISSUE THREAD

**Issue by HontoNoRoger** [yui/yeti#91]
My Yeti server has been started with `yeti --server --loglevel info` and crashed after some tests were run. Unfortunately I can't really reproduce it, therefore I don't know what's causing it.
Maybe the output will help you:

```
✗ Whoops! TypeError: Cannot call method 'serve' of null
    at Object.<anonymous> (/usr/local/lib/node_modules/yeti/lib/hub/batch.js:364:26)
    at BlizzardSession.invokeRPC (/usr/local/lib/node_modules/yeti/lib/blizzard/session.js:501:25)
    at BlizzardSession.onMessage (/usr/local/lib/node_modules/yeti/lib/blizzard/session.js:604:18)
    at BlizzardSession.EventEmitter.emit (/usr/local/lib/node_modules/yeti/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at BlizzardSession.bufferComplete (/usr/local/lib/node_modules/yeti/lib/blizzard/session.js:649:10)
    at BlizzardSession.EventEmitter.emit (/usr/local/lib/node_modules/yeti/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at /usr/local/lib/node_modules/yeti/lib/blizzard/session.js:813:22
    at Socket.emitter (/usr/local/lib/node_modules/yeti/lib/blizzard/session.js:782:21)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)

If you believe this is a bug in Yeti, please report it.
    https://github.com/yui/yeti/issues
    Yeti v0.2.29
    Node.js v0.10.25
```

**Comment by henryruhs** [comment]
:+1:
